
const nftDB=[
    {id:'1', title:'The Bitcoin Pizza', price:'12.000', pictureUrl:'/media/nft_1.png', stock:10, initial:1, category:'Bitcoin', description:'El 18 de mayo de 2010, un programador llamado Laszlo Hanyecz publicó en el foro de Bitcoin que quería usar 10,000 Bitcoins (valorados en $ 40 en ese momento) para comprar dos grandes pizzas de Papa John.“Pagaré 10,000 Bitcoins por dos pizzas. Lo mejor serían dos pizzas grandes, así que me queda algo para mañana. Puedes hacer tus propias pizzas. Una vez que hayan terminado, puede entregarlos en mi casa o coordinar una empresa de entrega para que los entregue, pero quiero usar Bitcoin para pagarlos. De esta manera, no tengo que pedirlos o hacerlos yo mismo, como el servicio de habitaciones en un hotel, entregados directamente a mi puerta. Serás muy feliz. Si estás interesado, contáctame. Podemos discutirlo más a fondo. Puede ser cualquier tipo de pizza con cebollas, pimientos, salchichas, champiñones e incluso una extraña cubierta de pescado está bien “.'},
    {id:'2', title:'Cyberpunk world', price:'27.345', pictureUrl:'/media/nft_2.png', stock:20, initial:2, category:'Ethereum', description:'subgénero de la ciencia ficción, conocido por reflejar visiones distópicas del futuro en las cuales se combinan la tecnología avanzada con un bajo nivel de vida. Originalmente el término cyberpunk fue utilizado para referirse al movimiento literario encabezado por Bruce Sterling, William Gibson y John Shirley que surgió durante la década de 1980 en el seno de la literatura de ciencia ficción.'},
    {id:'3', title:'Bitcoin Token render', price:'1.000', pictureUrl:'/media/nft_3.png', stock:100, initial:5, category:'Bitcoin', description:'concebida en 2008 por una entidad conocida bajo el seudónimo de Satoshi Nakamoto,10​ cuya identidad concreta se desconoce.11​ Satoshi trabajó en el código fuente de la aplicación de referencia junto a otros desarrolladores voluntarios hasta diciembre de 2010, momento en el que decidió concluir su actividad pública y dejar su desarrollo a cargo de la comunidad.'},
    {id:'4', title:'Japatonic Lite', price:'69.420', pictureUrl:'/media/nft_4.png', stock:7, initial:1, category:'Solana', description:'Desde pequeños, hemos crecido sin saberlo, mirando a la cultura japonesa con producciones como Mazinger Z, Bola de Dragón, Ultraman, Gundam, Transformers, Pokemon, Doraemon, Akira o Totoro entre muchos más. Casi se podría decir, que una parte de nuestro cerebro es japonesa, y a mucha honra, por supuesto. Esto me hace pensar, que tal vez por este motivo, pudiera ser que nos despierte tanto apego esta cultura. I was in Japan in January 2020 before there was a pandemic. I miss the times when it was possible to go there without any restrictions.'},
    {id:'5', title:'Bitcoin Saylor Node', price:'100.000.000', pictureUrl:'/media/nft_5.png', stock:4, initial:2, category:'Bitcoin', description:'The Bitcoin Full Node Sculpture is a cypherpunk chronometer, designed to work as a fully-functioning bitcoin full node and block explorer. Modeled after the ancient navigation tool, the astrolabe, it acts as a compass for the humble bitcoiner to set to true north. Visualizing the clock-and-calendar-like nature of Bitcoin stretching over 132 years, the sculpture represents a digital metronome ticking endlessly in the halls of time and space. This cyber-metronome ticks at a steady pace of “every 10 minutes,” as this is in perfect harmony with Bitcoin time. Like the Bitcoin software itself, the sculpture is a tool for personal growth, a tool that connects us to the community, a full circle. Also like the Bitcoin software, the design evolves with each new version.'},
]

export default nftDB